reservoir:
  target: duckdb
  outputs:
    duckdb:
     type: duckdb
     path: target/reservoir.duckdb
     threads: 12
    postgres:  
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: reservoir
      schema: dbo
      threads: 12
