CREATE TABLE DIM_DATE (
DATE_KEY PK String,
DTE_DMN_KEY String,
FULL_DTE Date,
DOFW Int32,
DOFM Int32,
DAY_NBR_OALL Int32,
WEEK_NBR_YR Int32,
DAY String,
MON Int32,
QTR Int32,
YEAR Int32,
EOM Int32,
PUB_HLDY_INDC Int32,
WKND_WDAY_INDC Int32
) ENGINE = MergeTree()
PRIMARY KEY DATE_KEY;

CREATE TABLE DIM_WELL_POOL (
WELL_RESERVOIR_KEY PK String,
LITHOSTRATIGRAPHIC_UNIT_NAME String,
REGIONAL_STAGE  String,
OFM_UNIQUEID NULL  String,
RESERVOIR_NAME_RU  String,
POOL_CADASTR_NUM  String
) ENGINE = MergeTree()
PRIMARY KEY WELL_RESERVOIR_KEY;

CREATE TABLE DIM_RESERVOIR (
WELL_RESERVOIR_KEY PK String,
WELL_NAME String,
ACTIVE_WELLBORE_NUMBER  Int32,
WELL_CLASS String,
SPUD_DATE Date,
OFM_UNIQUEID NULL  String,
RESERVOIR_NAME_RU  String,
) ENGINE = MergeTree()
PRIMARY KEY WELL_RESERVOIR_KEY;

CREATE TABLE FCT_PRODUCTION (
WELLPRODUCTION_ID PK String,
WELL_RESERVOIR_KEY String,
DATE_KEY String,
OIL Float32,
GAS Float32,
WATER Float32,
LIQUID Float32,
WELLUPTIMEDAYS Float32
) ENGINE = MergeTree()
PRIMARY KEY WELL_RESERVOIR_KEY;







